# Generated by Django 5.1.2 on 2024-11-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover_photo', models.ImageField(upload_to='events/covers/')),
                ('photos', models.ImageField(blank=True, null=True, upload_to='events/photos/')),
                ('video', models.FileField(blank=True, null=True, upload_to='events/videos/')),
            ],
        ),
    ]
