# Generated by Django 5.1.2 on 2024-11-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='event_photos/')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(upload_to='event_covers/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='event',
            name='photos',
        ),
        migrations.AlterField(
            model_name='event',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='event_videos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='photos',
            field=models.ManyToManyField(related_name='event_photos', to='events.eventphoto'),
        ),
    ]
