# Generated by Django 5.1.2 on 2024-11-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='link',
            field=models.URLField(max_length=250),
        ),
    ]
