# Generated by Django 5.1 on 2024-11-01 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='../static/imags/default_image.png', upload_to='')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=1000)),
                ('is_heading', models.BooleanField()),
                ('team_code', models.IntegerField()),
                ('facebook_link', models.CharField(max_length=1000)),
                ('linkedin_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
