# Generated by Django 5.1.2 on 2024-11-28 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contanct_us', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='members',
        ),
    ]
